# Dynamically generated by Matugen from wallpaper
set -g fish_color_normal e6e1df
set -g fish_color_command d2c4b7 -o
set -g fish_color_param e6e1df
set -g fish_color_keyword d2c4b7
set -g fish_color_quote cdc5be
set -g fish_color_redirection c8c7ba
set -g fish_color_end d2c4b7
set -g fish_color_error ffb4ab -o
set -g fish_color_gray 988f87
set -g fish_color_selection --background=4c463f
set -g fish_color_search_match --background=4c463f
set -g fish_color_operator c8c7ba
set -g fish_color_escape c8c7ba
set -g fish_color_autosuggestion 988f87
set -g fish_color_cancel ffb4ab
set -g fish_pager_color_prefix d2c4b7 -o
set -g fish_pager_color_completion e6e1df
set -g fish_pager_color_description 988f87
set -g fish_pager_color_selected_background --background=4c463f

# Theme variables for prompt
set -g prompt_color_primary d2c4b7
set -g prompt_color_secondary cdc5be
set -g prompt_color_tertiary c8c7ba
set -g prompt_color_text e6e1df
set -g prompt_color_error ffb4ab
set -g prompt_color_muted 988f87
