# Dynamically generated by Matugen from wallpaper
set -g fish_color_normal f3dddd
set -g fish_color_command ffb3b4 -o
set -g fish_color_param f3dddd
set -g fish_color_keyword ffb3b4
set -g fish_color_quote ffb3b4
set -g fish_color_redirection ffb875
set -g fish_color_end ffb3b4
set -g fish_color_error ffb4ab -o
set -g fish_color_gray a58a8a
set -g fish_color_selection --background=574142
set -g fish_color_search_match --background=574142
set -g fish_color_operator ffb875
set -g fish_color_escape ffb875
set -g fish_color_autosuggestion a58a8a
set -g fish_color_cancel ffb4ab
set -g fish_pager_color_prefix ffb3b4 -o
set -g fish_pager_color_completion f3dddd
set -g fish_pager_color_description a58a8a
set -g fish_pager_color_selected_background --background=574142

# Theme variables for prompt
set -g prompt_color_primary ffb3b4
set -g prompt_color_secondary ffb3b4
set -g prompt_color_tertiary ffb875
set -g prompt_color_text f3dddd
set -g prompt_color_error ffb4ab
set -g prompt_color_muted a58a8a
