# Dynamically generated by Matugen from wallpaper
set -g fish_color_normal e5e2e2
set -g fish_color_command c0c7d4 -o
set -g fish_color_param e5e2e2
set -g fish_color_keyword c0c7d4
set -g fish_color_quote c5c6cc
set -g fish_color_redirection d5c1ce
set -g fish_color_end c0c7d4
set -g fish_color_error ffb4ab -o
set -g fish_color_gray 8f9196
set -g fish_color_selection --background=45474b
set -g fish_color_search_match --background=45474b
set -g fish_color_operator d5c1ce
set -g fish_color_escape d5c1ce
set -g fish_color_autosuggestion 8f9196
set -g fish_color_cancel ffb4ab
set -g fish_pager_color_prefix c0c7d4 -o
set -g fish_pager_color_completion e5e2e2
set -g fish_pager_color_description 8f9196
set -g fish_pager_color_selected_background --background=45474b

# Theme variables for prompt
set -g prompt_color_primary c0c7d4
set -g prompt_color_secondary c5c6cc
set -g prompt_color_tertiary d5c1ce
set -g prompt_color_text e5e2e2
set -g prompt_color_error ffb4ab
set -g prompt_color_muted 8f9196
