-- Auto-generated by Matugen
return {
    primary = "#ffb3b4",
    on_primary = "#680017",
    surface = "#1b1111",
    surface_variant = "#574142",
    outline = "#a58a8a",
    outline_variant = "#574142",
}
