-- Auto-generated by Matugen
return {
    primary = "#d2c4b7",
    on_primary = "#372f26",
    surface = "#141312",
    surface_variant = "#4c463f",
    outline = "#988f87",
    outline_variant = "#4c463f",
}
