-- Auto-generated by Matugen
return {
    primary = "#c0c7d4",
    on_primary = "#2a313b",
    surface = "#131314",
    surface_variant = "#45474b",
    outline = "#8f9196",
    outline_variant = "#45474b",
}
