
monitor = eDP-1, 1920x1080@144, 0x0, 1


# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun
$browser = brave

#################
### AUTOSTART ###
#################


exec-once = nm-applet &
exec-once = waybar
exec-once = swaync
exec-once = swww-daemon && swww restore
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = fcitx5 -d -r


#############################
### ENVIRONMENT VARIABLES ###
#############################


env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = GTK_IM_MODULE=ibus
env = QT_IM_MODULE=ibus
env = XMODIFIERS=@im=ibus


# Import modular configs
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/settings.conf
source = ~/.config/hypr/animation.conf
