
# Input devices
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

gesture = 3, horizontal, workspace
# Misc tweaks
misc {
    # force_default_wallpaper = -1
    disable_hyprland_logo = false
    on_focus_under_fullscreen = 1
}

cursor{
    no_hardware_cursors = 0
  }

group {
    groupbar {
        enabled = false
    }
}
