
# Suppress maximize events globally
windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

# Fix XWayland drag issues
windowrule {
    name = fix-xwayland-drags
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run floating
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}


layerrule {
  name = wlogout-blur
  match:namespace = ^logout_dialog$
  blur = true
}

layerrule {
    name = rofi-style
    match:namespace = rofi
    blur = yes
    dim_around = true
    animation = popin 85%
    ignore_alpha = 0.3
}

