# General layout
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgb(cba6f7)
    col.inactive_border = rgb(45475a)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
    border_size = 0
}

# Decorations
decoration {
    rounding = 16
    rounding_power = 2
    active_opacity = 1.0


    blur {
        enabled = true
        size = 5
        passes = 3
        vibrancy = 0.1696
    }
}


