
monitor = eDP-1, 1920x1080@144, 0x0, 1


# Set programs that you use
$terminal = kitty
$fileManager = kitty -e yazi
$menu = rofi -show drun
$browser = brave

#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = pypr
exec-once = awww-daemon
exec-once = qs -c overview
exec-once = hypridle
# exec-once = wl-paste --type text --watch cliphist store
# exec-once = wl-paste --type image --watch cliphist store
exec-once = clipse -listen
exec-once = gnome-keyring-deamon --start --components=secrets
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
exec-once = swaync
exec-once = sleep 3 && ~/.config/hypr/scripts/notify-sequence.sh

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct


# Import modular configs
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/settings.conf
source = ~/.config/hypr/animation.conf
