
# Suppress maximize events globally
# windowrule {
#     name = suppress-maximize-events
#     match:class = .*
#     suppress_event = maximize
# }

# Fix XWayland drag issues
# windowrule {
#     name = fix-xwayland-drags
#     match:xwayland = true
#     match:float = true
#     match:fullscreen = false
#     match:pin = false
#     no_focus = true
# }

# Hyprland-run floating
# windowrule {
#     name = move-hyprland-run
#     match:class = hyprland-run
#     move = 20 monitor_h-120
#     float = yes
# }


layerrule {
  name = wlogout-blur
  match:namespace = ^logout_dialog$
  blur = true
}

layerrule {
    name = rofi-style
    match:namespace = rofi
    blur = yes
    dim_around = true
    animation = popin 85%
    ignore_alpha = 0.3
}


windowrule {
    name = xdg-float
    match:class = xdg-desktop-portal-gtk

    float = true
    center = true
    size = 1100 750

    animation = popin 90%
}

windowrule {
    name = sysmon-preview
    match:class = ^(floating_mem)$

    float = true
    center = true
    size = 1000 600
    
    # Optional styling to make it feel like a widget
    animation = popin 90%
    dim_around = true
}

windowrule {
    name = clipboard-manager
    match:class = ^(clipse-gui)$

    float = true
    center = true
    size = 640 700
    
    # Widget-style aesthetics
    animation = popin 90%
    dim_around = true
}
