# Dynamically generated by Matugen from wallpaper
set -g fish_color_normal {{ colors.on_surface.default.hex_stripped }}
set -g fish_color_command {{ colors.primary.default.hex_stripped }} -o
set -g fish_color_param {{ colors.on_surface.default.hex_stripped }}
set -g fish_color_keyword {{ colors.primary.default.hex_stripped }}
set -g fish_color_quote {{ colors.secondary.default.hex_stripped }}
set -g fish_color_redirection {{ colors.tertiary.default.hex_stripped }}
set -g fish_color_end {{ colors.primary.default.hex_stripped }}
set -g fish_color_error {{ colors.error.default.hex_stripped }} -o
set -g fish_color_gray {{ colors.outline.default.hex_stripped }}
set -g fish_color_selection --background={{ colors.surface_variant.default.hex_stripped }}
set -g fish_color_search_match --background={{ colors.surface_variant.default.hex_stripped }}
set -g fish_color_operator {{ colors.tertiary.default.hex_stripped }}
set -g fish_color_escape {{ colors.tertiary.default.hex_stripped }}
set -g fish_color_autosuggestion {{ colors.outline.default.hex_stripped }}
set -g fish_color_cancel {{ colors.error.default.hex_stripped }}
set -g fish_pager_color_prefix {{ colors.primary.default.hex_stripped }} -o
set -g fish_pager_color_completion {{ colors.on_surface.default.hex_stripped }}
set -g fish_pager_color_description {{ colors.outline.default.hex_stripped }}
set -g fish_pager_color_selected_background --background={{ colors.surface_variant.default.hex_stripped }}

# Theme variables for prompt
set -g prompt_color_primary {{ colors.primary.default.hex_stripped }}
set -g prompt_color_secondary {{ colors.secondary.default.hex_stripped }}
set -g prompt_color_tertiary {{ colors.tertiary.default.hex_stripped }}
set -g prompt_color_text {{ colors.on_surface.default.hex_stripped }}
set -g prompt_color_error {{ colors.error.default.hex_stripped }}
set -g prompt_color_muted {{ colors.outline.default.hex_stripped }}
