-- Auto-generated by Matugen
return {
    primary = "{{ colors.primary.default.hex }}",
    on_primary = "{{ colors.on_primary.default.hex }}",
    surface = "{{ colors.surface.default.hex }}",
    surface_variant = "{{ colors.surface_variant.default.hex }}",
    outline = "{{ colors.outline.default.hex }}",
    outline_variant = "{{ colors.outline_variant.default.hex }}",
}
